#!/usr/bin/env python3
"""Generate complete Android language resources, or check them without writing."""
import argparse
import json
from pathlib import Path
import xml.etree.ElementTree as ET
import validate_catalog as validator

EXCLUDED = frozenset({"app_name"})  # Preserve Alpha/Mock identity from variant resources.


def android_literal(value):
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("'", "\\'")
    escaped = escaped.replace("\n", "\\n").replace("\t", "\\t").replace("\r", "\\u000d")
    if escaped.startswith(("@", "?")):
        escaped = "\\" + escaped
    return '"' + escaped + '"'


def render(catalog):
    root = ET.Element("resources")
    root.append(ET.Comment(" Generated by localization/android_resources.py; edit catalog JSON instead. "))
    for key in sorted(catalog.keys() - EXCLUDED):
        ET.SubElement(root, "string", name=key).text = android_literal(catalog[key])
    ET.indent(root, space="    ")
    return ET.tostring(root, encoding="utf-8", xml_declaration=True) + b"\n"


def generate(directory, res_root, check=False):
    source = validator.source_catalog(directory / "source.json")
    rendered = {}
    # Validate every file before creating any destination directory or changing existing output.
    for tag in validator.LANGUAGES:
        catalog = validator.decode_json((directory / f"{tag}.json").read_text(encoding="utf-8"))
        errors = validator.validate(source, catalog)
        if errors:
            raise ValueError(f"{tag}: {', '.join(errors)}")
        rendered[tag] = render(catalog)
    drift = []
    changed = []
    for tag, content in rendered.items():
        path = res_root / f"values-{tag}" / "strings.xml"
        if path.is_file() and path.read_bytes() == content:
            continue
        changed.append(tag)
        if check:
            drift.append(tag)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
    return {"resourcesPerLanguage": len(source.keys() - EXCLUDED), "changed": changed, "drift": drift}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--directory", type=Path, default=validator.ROOT / "localization/catalog")
    parser.add_argument("--res-root", type=Path, default=validator.ROOT / "mobile/src/main/res")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        result = generate(args.directory, args.res_root, args.check)
    except (OSError, ValueError) as error:
        print(json.dumps({"error": str(error)}, ensure_ascii=False))
        return 2
    print(json.dumps(result, ensure_ascii=False))
    return 1 if result["drift"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
