package io.openhoyi.mobile

import io.openhoyi.protocol.CoffeeCommands
import io.openhoyi.protocol.StartParameters
import java.io.InputStream

/** Adapts local factory metadata to the exact temporary-curve command used by the old app. */
object FactoryCurveAdapter {
    fun profile(curve: FactoryCurve, scaleConnected: Boolean): CurveProfile {
        // Legacy m(curve): when a scale is connected, max(flow, ceil(4 * target grams)).
        val maximumWater = if (scaleConnected && curve.weightTenthsGram > 0)
            maxOf(curve.flowMl, (curve.weightTenthsGram * 2 + 4) / 5)
        else curve.flowMl
        val targets = curve.targets
        val flows = curve.segmentFlowMl
        val parameters = StartParameters(curve.pressureLogic, curve.variableFlowLogic, curve.segmentCount, 7,
            curve.temperatureC, maximumWater, false, curve.preinfusionSeconds,
            targets[0], targets[1], targets[2], targets[3],
            flows[0] * 10, curve.firstDurationSeconds, flows[1] * 10, flows[2] * 10, flows[3] * 10)
        return CurveProfile(curve.id, curve.name,
            if (scaleConnected && curve.weightTenthsGram > 0) "达到目标重量后停止" else "由咖啡机按水量结束",
            if (scaleConnected) curve.weightTenthsGram * 10 else 0,
            parameters, if (scaleConnected) curve.weightCompensationTenthsGram * 10 else 0, scaleConnected)
    }
}

/** Independent byte oracle generated by executing only the legacy startTempChart encoder. */
class FactoryWireProof private constructor(
    private val factory: Map<String, FactoryCurve>,
    private val frames: Map<String, Pair<String, String>>,
) {
    fun allowedFrames(): Set<String> = frames.values.flatMap { listOf(it.first, it.second) }.toSet()
    fun expected(id: String, scaleConnected: Boolean): String? =
        frames[id]?.let { if (scaleConnected) it.second else it.first }

    fun validated(profile: CurveProfile): Boolean {
        val mode = profile.scaleMode ?: return false
        val curve = factory[profile.id] ?: return false
        if (profile != FactoryCurveAdapter.profile(curve, mode)) return false
        return runCatching { CoffeeCommands.start(profile.parameters).frame.hex() }.getOrNull() ==
            expected(profile.id, mode)
    }

    companion object {
        fun load(input: InputStream, curves: List<FactoryCurve>): FactoryWireProof {
            require(curves.size == 100 && curves.map { it.id }.toSet().size == 100)
            val lines = input.bufferedReader(Charsets.UTF_8).use { it.readLines() }
            require(lines.firstOrNull() == "# factory-wire-v1\tsource-sha256=${FactoryCurveCatalog.SOURCE_SHA256}")
            require(lines.size == curves.size + 1)
            val frames = linkedMapOf<String, Pair<String, String>>()
            for ((index, curve) in curves.withIndex()) {
                val fields = lines[index + 1].split('\t')
                require(fields.size == 3 && fields[0] == curve.id) { "factory wire ID at $index" }
                require(fields.drop(1).all { it.matches(Regex("02[0-9A-F]{38}")) })
                for (mode in listOf(false, true)) {
                    val actual = CoffeeCommands.start(FactoryCurveAdapter.profile(curve, mode).parameters).frame.hex()
                    require(actual == fields[if (mode) 2 else 1]) { "factory wire mismatch at ${curve.id} scale=$mode" }
                }
                frames[curve.id] = fields[1] to fields[2]
            }
            return FactoryWireProof(curves.associateBy(FactoryCurve::id), frames)
        }
    }
}
